
ALTER TABLE `paper_anwser`
  ADD COLUMN `tempId` INT(10) NULL DEFAULT NULL AFTER `tempId`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='exam';
SHOW TABLE STATUS FROM `exam`;
SHOW FUNCTION STATUS WHERE `Db`='exam';
SHOW PROCEDURE STATUS WHERE `Db`='exam';
SHOW TRIGGERS FROM `exam`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='exam';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='exam' AND TABLE_NAME='paper_anwser' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `paper_anwser` FROM `exam`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='exam'   AND TABLE_NAME='paper_anwser'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='exam'   AND TABLE_NAME='paper_anwser'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* Entering session "Local MySql" */
SHOW CREATE TABLE `exam`.`paper_anwser`;
